import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { Outfit } from 'next/font/google';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Magna-AI',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: 'iconButton',
          logoImageUrl: '/ai12.png',
        },
        variables: {
          colorBackground: '#121B22',
          colorPrimary: '#25D366',
          colorText: '#E9EDEF',
          colorInputText: 'white',
          colorInputBackground: '#1E2A33', // ✅ Add this
          colorAlphaShade: '#25D36640',
          colorDanger: '#ff0000',
          colorTextOnPrimaryBackground: '#1E2A33',
        },
        elements: {
          socialButtonsIconButton:
            'border bg-[#1E2A33] border-[#25D366] hover:bg-[#25D36620]',
        },
      }}
    >
      <html lang="en">
        <body className={outfit.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
